# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main", "cobertura-ci-loop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run JUnit tests with Maven
      run: mvn test
    - name: ReportGenerator
    # You may pin to the exact commit or the version.
    # uses: danielpalme/ReportGenerator-GitHub-Action@4d510cbed8a05af5aefea46c7fd6e05b95844c89
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
        reports: target/site/jacoco/jacoco.xml # default is coverage.xml
        # The directory where the generated report should be saved.
        # targetdir: # default is coveragereport
        # The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, CsvSummary, Html, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlSummary, Html_BlueRed_Summary, JsonSummary, Latex, LatexSummary, lcov, MHtml, SvgChart, SonarQube, TeamCitySummary, TextSummary, Xml, XmlSummary
        reporttypes: HtmlInline;Cobertura;TextSummary
        # Optional directories which contain the corresponding source code (separated by semicolon). The source directories are used if coverage report contains classes without path information.
        sourcedirs: src/main/java/com/dev/sweproject # optional, default is 
        # The verbosity level of the log messages. Values: Verbose, Info, Warning, Error, Off
        # verbosity: # optional, default is Info
        # Optional title.
        title: JaCoCo code coverage report
    - name: JaCoCoSummary
      run: cat coveragereport/Summary.txt
